library(astsa)
library(vars)
soi=ts(soi)
rec=ts(rec)
par(mfrow=c(3,2))
ts.plot(soi)
ts.plot(rec)
acf(soi,48,main="sample ACF of SOI")
acf(rec,48,main="sample ACF of REC")
ccf(soi,rec,48,main="sample CCF of SOI and REC")
ccf(rec,soi,48,main="sample CCF of REC and SOI")
fish = ts.intersect(rec, soiL6=lag(soi,-6), dframe=TRUE)
plot(rec~soiL6,data=fish,pch=16)
trend=c(1:447)
lm=lm(rec~trend+soiL6, data=fish, na.action=NULL)
summary(lm)
resid_lm=residuals(lm)
par(mfrow=c(2,1))
qqnorm(resid_lm,ylab="Residual")
qqline(resid_lm)
plot(trend,resid_lm,xlab="time",ylab="Residuals",ylim=max(abs(resid_lm))*c(-1,1),pch=16,main="Plot of Residuals vs time")
abline(h=0,lty=2)
